---
- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
  - name: register self IP
    shell: ifconfig new | awk '/t addr:/{gsub(/.*:/,"",$2);print$2}' #later on it will be eth1 for every VM
    register: selfIP

  - name: Adding self IP in named conf
    replace:
      dest: /etc/nginx/nginx.conf
      regexp: '100.100.100.10'
      replace: "{{ lookup('env', 'centralDNS1_IP') }}"
      backup: yes

  - name: Adding self IP in named conf
    replace:
      dest: /etc/nginx/nginx.conf
      regexp: '100.100.100.20'
      replace: "{{ lookup('env', 'centralDNS2_IP') }}"
      backup: yes
