---
- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
  - name: register self IP
    shell: ifconfig new | awk '/t addr:/{gsub(/.*:/,"",$2);print$2}' #later on it will be eth1 for every VM
    register: selfIP

  - debug:
      msg: "{{ selfIP.stdout }}"

  - name: Adding self IP in named conf
    replace:
      dest: /etc/named.conf
      regexp: '192.168.199.104'
      replace: "{{ selfIP.stdout }}"
      backup: yes
