tv.net_VPC2_DNS1 : 
c2S2VM2_VPC2 : 21795
fb.net_VPC2_DNS1 : 
c2S1VM1_VPC2 : 21486
fb.com_VPC1_DNS1 : 
VPC1_DNS1 : 20381
cnu.com_VPC1_DNS1 : 
VPC2_DNS1 : 20224
VPC1_DNS2 : 83453
fb.com_NCSU_DNS1 : 
cnu.com_NCSU_DNS1 : 
c1S1VM2_VPC1 : 21643
VPC2_DNS2 : 20540
c1S1VM2_NCSU : 
NCSU_DNS2 : 
c1S2VM1_NCSU : 
c1S2VM1_VPC1 : 84488
NCSU_DNS1 : 
