---
  - name: create Namespace
    command: ip netns add "{{ item.value.VPC_name }}"
    with_dict: "{{ VPC }}"

  - name: create Veth pair
    command: ip link add "{{ item.value.VPC_name }}_host" type veth peer name "host_{{ item.value.VPC_name }}"
    with_dict: "{{ VPC }}"

  - name: attach veth pair to namespace
    command: ip link set "{{ item.value.VPC_name }}_host" netns "{{ item.value.VPC_name }}"
    with_dict: "{{ VPC }}"

  - name: make interface attached to namespace UP
    command: ip netns exec "{{ item.value.VPC_name }}" ip link set "{{ item.value.VPC_name }}_host" up
    with_dict: "{{ VPC }}"

  - name: make veth interface in host as UP
    command: ip link set "host_{{ item.value.VPC_name }}" up
    with_dict: "{{ VPC }}"

  - name: add ip to veth interface in host
    command: ip addr add 10.10.10.1/24 dev "host_{{ item.value.VPC_name }}"
    with_dict: "{{ VPC }}"

  - name: create bridge and make it up for VPC DNS
    shell: sudo brctl addbr central_br | sudo ip link set central_br up

  - name: create Veth pair from central DNS to bridge
    command: ip link add central_DNS1_br type veth peer name br_central_DNS1

  - name: create Veth pair from secondary central DNS to bridge
    command: ip link add central_DNS2_br type veth peer name br_central_DNS2
    
  - name: create Veth pair ngnix to bridge
    command: ip link add ngnix_br type veth peer name br_ngnix

  - name: create Veth pair from bridge to host
    command: ip link add host_br type veth peer name br_host

  - name: Add all bridge interface to bridge from central DNS and ngnix and host
    command: sudo brctl addif central_br br_central_DNS1 br_central_DNS2 br_ngnix br_host

  - name: attach veth pair interface to central containers from central bridge
    shell: sudo ip link set $(python ./roles/infra/tasks/getDockerPID.py central_DNS1) dev central_DNS1_br

  - name: make interface up
    shell: sudo docker exec -it --privileged central_DNS1 ip link set dev central_DNS1_br up

  #- name: add ip to these interfaces
  #  command: sudo nsenter -t $(python ./roles/infra/tasks/getDockerPID.py central_DNS1) -n ip addr add $(python ./roles/infra/tasks/ipassign.py "{{item.value.VPC_name}}" subnet "{{item.value.Subnet1.Subnet_IP}}") dev central_DNS1_br

  - name: attach veth pair interface to secondary central containers from central bridge
    command: sudo ip link set $(python ./roles/infra/tasks/getDockerPID.py central_DNS2) dev central_DNS2_br

  - name: make interface up
    command: sudo docker exec -it --privileged central_DNS2 ip link set dev central_DNS2_br up

 # - name: add ip to these interfaces
 #   command: sudo nsenter -t $(python ./roles/infra/tasks/getDockerPID.py central_DNS2) -n ip addr add $(python ./roles/infra/tasks/ipassign.py "{{item.value.VPC_name}}" subnet "{{item.value.Subnet1.Subnet_IP}}") dev central_DNS2_br

  - name: attach veth pair interface to containers
    command: sudo ip link set $(python ./roles/infra/tasks/getDockerPID.py ngnix) dev ngnix_br

  - name: make interface up
    command: sudo docker exec -it --privileged nginx ip link set dev ngnix_br up

  #- name: add ip to these interfaces
  #  command: sudo nsenter -t $(python ./roles/infra/tasks/getDockerPID.py ngnix) -n ip addr add $(python ./roles/infra/tasks/ipassign.py "{{item.value.VPC_name}}" subnet "{{item.value.Subnet1.Subnet_IP}}") dev ngnix_br

