---
  - name: create Namespace
    command: ip netns add "{{ item.value.VPC_name }}"
    with_dict: "{{ VPC }}"

  - name: create Veth pair
    command: ip link add "{{ item.value.VPC_name }}_host" type veth peer name "host_{{ item.value.VPC_name }}"
    with_dict: "{{ VPC }}"

  - name: attach veth pair to namespace
    command: ip link set "{{ item.value.VPC_name }}_host" netns "{{ item.value.VPC_name }}"
    with_dict: "{{ VPC }}"

  - name: make interface attached to namespace UP
    command: ip netns exec "{{ item.value.VPC_name }}" ip link set "{{ item.value.VPC_name }}_host" up
    with_dict: "{{ VPC }}"

  - name: make veth interface in host as UP
    command: ip link set "host_{{ item.value.VPC_name }}" up
    with_dict: "{{ VPC }}"

  - name: add ip to veth interface in host
    command: ip addr add 10.10.10.1/24 dev "host_{{ item.value.VPC_name }}"
    with_dict: "{{ VPC }}"
