---
  - name: copy the csv yml to vars in current task
    command: cp ./userInput.yml ./roles/infra/vars/main.yml

  - name: create containers for DNS VPC
    command: sudo docker run -itd --privileged --name="{{item.value.VPC_name}}_DNS1" --hostname="{{item.value.VPC_name}}_DNS1" soupsubnetdns
    with_dict: "{{ VPC }}"

  - name: create secondary containers for DNS VPC
    command: sudo docker run -itd --privileged --name="{{item.value.VPC_name}}_DNS2" --hostname="{{item.value.VPC_name}}_DNS2" soupsubnetdns
    with_dict: "{{ VPC }}"

  - name: create container for DNS in first subnets of all VPC
    command: sudo docker run -itd --privileged --name="{{item.value.Subnet1.Subnet_name}}_{{item.value.VPC_name}}_DNS" --hostname="{{item.value.Subnet1.Subnet_name}}_{{item.value.VPC_name}}_DNS" soupsubnetdns
    with_dict: "{{ VPC }}"

  - name: create container for DNS in second subnets of all VPC
    command: sudo docker run -itd --privileged --name="{{item.value.Subnet2.Subnet_name}}_{{item.value.VPC_name}}_DNS" --hostname="{{item.value.Subnet2.Subnet_name}}_{{item.value.VPC_name}}_DNS" soupsubnetdns
    with_dict: "{{ VPC }}"

  - name: create container in first subnets of all VPC
    command: sudo docker run -itd --privileged --name="{{item.value.Subnet1.VM_name}}_{{item.value.VPC_name}}" --hostname="{{item.value.Subnet1.VM_name}}_{{item.value.VPC_name}}" soupimage
    with_dict: "{{ VPC }}"

  - name: create container in second subnets of all VPC
    command: sudo docker run -itd --privileged --name="{{item.value.Subnet2.VM_name}}_{{item.value.VPC_name}}" --hostname="{{item.value.Subnet2.VM_name}}_{{item.value.VPC_name}}" soupimage
    with_dict: "{{ VPC }}"


