---
  - name: copy the user yml to vars in current task
    command: cp ./editInput.yml ./roles/edit/vars/main.yml
    
  - name: create Tunnel
    command: ip netns exec "{{ item.value.VPC_name }}" ip tunnel add gretun1 mode gre 60.60.60.10 remote 10.10.10.10
    with_dict: "{{ VPC }}"
 
   - name: create Tunnel
    command: ip netns exec "{{ item.value.VPC_name }}" sudo ip link set dev gretun1 up
    with_dict: "{{ VPC }}"

  - name: Add tunnel route
    command: ip netns exec "{{ item.value.VPC_name }}" ip route add "{{item.value.Subnet1.Subnet_name}}" dev gretun1
    with_dict: "{{ VPC }}"
